workflows:
  ios-unsigned:
    name: Sales Goal App iOS
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: 3.47.5
      xcode: latest

    scripts:
      - name: Flutter packages
        script: flutter pub get

      - name: Build iOS without code signing
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/**/*.app
      - /tmp/xcodebuild_logs/*.log